name: okhttp_http
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  async: ^2.11.0
  http: ^1.2.1
  jni: ^0.7.2
  path: ^1.8.0

dev_dependencies:
  dart_flutter_team_lints: ^2.1.1
  http_client_conformance_tests:
    path: ../http_client_conformance_tests/
  jnigen: ^0.7.0
  lints: ^3.0.0
  test: ^1.24.0
